apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer 
  selector:
    app: restaurant-api # Conecta el balanceador con los clones 
  ports:
    - protocol: TCP
      port: 80        # El puerto expuesto al mundo
      targetPort: 8080 # El puerto interno de los clones de Go