# ==================================================================
# Configuración: Config Server (mongod)
# Propósito: Almacena metadatos y configuración del clúster
# ==================================================================

sharding:
  clusterRole: configsvr
replication:
  replSetName: configRS
security:
   keyFile: /etc/mongo-secrets/keyfile
net:
  bindIpAll: true
  port: 27017